config/routes.rb
Postit::Application.routes.draw do
  get "static_pages/about"

  get "static_pages/contact"

  root to: 'posts#index'
  get "/register",  to: 'users#new'
  get "/login",     to: 'sessions#new'
  post "/login",    to: 'sessions#create'
  get "/logout",    to: 'sessions#destroy'
  get "/about",     to: 'static_pages#about'

  #resources :posts
  resources :posts, except:[:destroy] do
    member do
      post 'vote'   
    end

    #resources :categories, only:[:show, :index]
    resources :comments do
      member do
        post 'vote'
      end
    end
  end

  resources :users, only:[:create, :edit, :show] do

  end

  resources :categories, except:[:destroy] do
    resources :posts, only:[:show]
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  belongs_to  :user
  has_many    :posts_categories
  has_many    :categories, through: :posts_categories
  has_many    :comments, order: 'created_at desc'
  has_many    :votes, as: :voteable
  # has_many    :postcomments
  # has_many    :comments, through: :postcomments
  validates :title, presence: true
  validates :url, presence: true, uniqueness: true

  after_validation :generate_slug

  def generate_slug
    #remove stop words 
    slug = self.title.dup
    #stop_words = stopwords
    words = slug.scan(/\w+/)

    slug_words = words.select { |word| !STOP_WORDS.include?(word)}

    if slug_words.size > 0

      slug = slug_words.join(' ')
    else
      slug = self.title.dup
    end
    
    #slug = self.title.dup

    #blow away apostrophes
    slug.gsub! /['`]/,""

    # @ --> at, and & --> and
    slug.gsub! /\s*@\s*/, " at "
    slug.gsub! /\s*&\s*/, " and "

    #replace all non alphanumeric, underscore or periods with underscore
    slug.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '_'

     #convert double underscores to single
    slug.gsub! /_+/,"_"

     #strip off leading/trailing underscore
    slug.gsub! /\A[_\.]+|[_\.]+\z/,""

    slug.downcase!
     
    count = 0
    final_slug = slug
    test = nil
    test = Post.where("slug = ?",final_slug).first

    #test = Post.find_by_slug(self.slug)
    while test && (self.new_record? || test != self)
      count += 1
      final_slug = slug + "_" + count.to_s
      
      test = nil
      test = Post.where("slug = ?",final_slug).first

      #test = Post.find_by_slug(self.slug)
    end
    self.slug = final_slug
  end

  def to_param
    self.slug
  end

  def total_votes
    self.votes.where(vote: true).size - self.votes.where(vote: false).size
  end
end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  include ActiveModel::ForbiddenAttributesProtection

  before_filter :find_post, only: [:show, :edit, :update, :vote]
  before_filter :require_user, only: [:new, :create, :edit, :update, :vote]

  def index
    @posts = Post.all.reverse
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    #@post = Post.new(params[:post])
    @post.user_id = current_user.id

    if params[:commit] == "Self Populate"
      auto_feed = rss_in(params[:rss]);
      @post.title = auto_feed[:title]
      @post.description = auto_feed[:description]
      @post.url = auto_feed[:url]
      render 'edit'
    else
    
      if @post.save
        #flash[:success] = "Your post has been saved!"
        redirect_to @post, :success => "Your post has been saved!"
      else
        render 'new'
      end
    end
  end

  def show
    #@post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    #@post = Post.find(params[:id])
    @comment = Comment.new
  end

  def update
    #@post = Post.find(params[:id]) 

    if @post.update_attributes(post_params)
      redirect_to @post, :success => "Your post has been edited and saved!"
    else
      render 'edit'
    end
  end

  def vote
    unless user_voted?(@post)
      Vote.create(user: current_user, voteable: @post, vote: params[:vote])
    end
    
    respond_to do |format|
      format.html do  
        flash[:success] = "Your vote has been saved!"
        redirect_to :back
      end

      format.js
    end
  end

  private

  def find_post
    #@post = Post.find_by_slug(params[:id]) 
    @post = Post.where(slug:params[:id]).first
  end

  def post_params

    params.permit(post: [:title, :description, :url, :category_ids => [] ])[:post]

  end
end

app/views/posts/_form.html.erb
<div class="span6 offset1">
  <%= form_for @post do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'input-xxlarge' %>
        
    <%= f.label :description %>
    <%= f.text_area :description, :size => "66x2" %>

    <%= f.label :url %>
    <%= f.url_field :url, class: 'input-xxlarge' %><br />

    <%= f.label :category %>
    <%= f.select :category_ids, Category.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %><br />

    <%= f.submit class: "btn btn-large btn-info"  %><br>
</div>
    <% if @post.title.nil? %>
      <div class='clearfix'></div>
      <div>      
        <hr>
        <h4>(Optional) Chose feed to self populate form.<small> You will be given the chance to edit the post after the self populate.</small></h4>
        <hr>
      </div>
        <div class="span6 offset1">
          <label class="radio">
            <%= radio_button_tag(:rss, "1") %>
            <%= label_tag(:rss_1, "OSHA News Feed") %>
          </label>

          <label class="radio">
            <%= radio_button_tag(:rss, "2") %>
            <%= label_tag(:rss_2, "OHS Online News Feed") %>
          </label>

          <label class="radio">
            <%= radio_button_tag(:rss, "3") %>
            <%= label_tag(:rss_2, "CSB New Video") %>
          </label>

          <label class="radio">
            <%= radio_button_tag(:rss, "4") %>
            <%= label_tag(:rss_2, "CSB Safety News") %>
          </label>

          <label class="radio">
            <%= radio_button_tag(:rss, "4") %>
            <%= label_tag(:rss_2, "NFPA News Release") %>
          </label>

          <%= f.submit "Self Populate", name: "commit", class: "btn btn-large btn-info"  %>
        </div>
    <% end %>
<% end %> 

app/views/posts/_vote.html.erb
<div class='well well-small span'>
  <% if logged_in? && user_voted?(post) == false %> 
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true, id: "post_vote_true_#{post.id}"  do %>
      <span class="label label-success"><i class='icon-circle-arrow-up'></i></span>
    <% end %>
  <% end %>
  <div class='vote_text'>
    <span class='vote_text' id="post_<%= post.id %>_votes"><strong><%= post.total_votes %></strong></span>
  </div>
  <% if logged_in? && user_voted?(post) == false %>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true, id: "post_vote_false_#{post.id}"  do %>
      <span class="label label-important"><i class='icon-circle-arrow-down'></i></span>
    <% end %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<hr>
<%= render 'form' %>

app/views/posts/index.html.erb
<% provide(:title, "Posts") %>
<h2>Posts</h2>
<hr>
<%= render '/shared/posts' %>

app/views/posts/new.html.erb
<h2>New Post</h2>
<hr>
<%= render 'form' %>

app/views/posts/show.html.erb
<% provide(:title, @post.title ) %>
<h2><%= @post.title %></h2>
<hr>
<div class='span11'>
  <%= render :partial => '/posts/vote', :locals => {:post => @post } %>
  <div class='well well-small offset1'>
    <h4 class='media-heading'><%= link_to @post.title, @post.url %><small> by <%= @post.user.username %> on <%= display_datetime(@post.created_at) %></small></h4>
    <p><%= @post.description %></p>

    <%if @post.categories.size > 0 %>
      <ul class='inline'>Post Categories:
        <%= render @post.categories %>
      </ul>
    <% end %>
    <ul class='inline'>
      <% if logged_in? && current_user.id == @post.user_id %>
        <li> <%= link_to 'Edit Post', edit_post_path(@post) %></li>
        <li>|</li>
      <% end  %>
      <li><%= link_to 'Back to Posts', posts_path %></li>
    </ul>
  </div>
  <% if logged_in? %>
    <div class="clearfix"></div>
      <hr>
      <h4>Add / Edit Comment:</h4>
      <hr>
      <div class="offset1">
      <%= render '/comments/form' %>
    </div>
  <% end %> 
  <hr>
  <h4>Comments on <%= @post.title %></h4>
  <hr>
  <% @post.comments.reload %>
  <%= render @post.comments %>
</div>

app/views/posts/vote.js.erb
$("#post_<%= @post.id %>_votes").html("<strong><%= @post.total_votes %></strong>");
$("#post_vote_true_<%= @post.id %>").hide("slow");
$("#post_vote_false_<%= @post.id %>").hide("slow");