config/routes.rb
Postit::Application.routes.draw do
  get "static_pages/about"

  get "static_pages/contact"

  root to: 'posts#index'
  get "/register",  to: 'users#new'
  get "/login",     to: 'sessions#new'
  post "/login",    to: 'sessions#create'
  get "/logout",    to: 'sessions#destroy'
  get "/about",     to: 'static_pages#about'

  #resources :posts
  resources :posts, except:[:destroy] do
    member do
      post 'vote'   
    end

    #resources :categories, only:[:show, :index]
    resources :comments do
      member do
        post 'vote'
      end
    end
  end

  resources :users, only:[:create, :edit, :show] do

  end

  resources :categories, except:[:destroy] do
    resources :posts, only:[:show]
  end
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small>
    Rails - Health and Safety Post it Board by Kirk Jarvis
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= image_tag("psp32.png", :class => "nav_img") %></li>
  <li><%= link_to "Health & Safety Posts", root_path, :class => 'active' %></li>
  <li class="divider-vertical"></li>

  <% if logged_in? %>
    <li>
      <%= link_to 'New Post', new_post_path, :class => 'active' %>
    </li>
    <li class="divider-vertical"></li>
  <% end %>
  <li class='dropdown'>
    <a href='#' class="dropdown-toggle" data-toggle="dropdown">
      Categories
      <b class='caret'></b>
    </a>
    <ul class="dropdown-menu">
      <% categories = Category.all %>

        <% categories.each do | category | %>
          <li><%= link_to "#{category.name}", category_path(category) %></li>
        <% end %>
        <li class='divider'><li>
        <li><%= link_to "Show all", categories_path %></li>

      <% if logged_in? %>
        <li class='divider'><li>
        <li><%= link_to "Add Category", new_category_path %></li>
      <% end %>
    </ul>
  </li>
</ul>

<% if logged_in? %>
  <ul class='nav pull-right'>
    <li class='dropdown'>
      <a href='#' class="dropdown-toggle" data-toggle="dropdown">
        Welcome <%= current_user.username %>
      <b class='caret'></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to  edit_user_path(current_user) do %>
            <i class='icon-pencil'></i> Edit Profile
          <% end %>
      </li>
      <li><%= link_to  user_path(current_user) do %>
            <i class='icon-user'></i> View Profile
          <% end %>
      </li>
    </ul>
    </li>
    <li class="divider-vertical"></li>
    <li><%= link_to "Log out", "/logout" %></li>
  </ul>
<% else %>
  <ul class='nav pull-right'>
    <li><%= link_to "Register", '/register' %></li>
    <li class="divider-vertical"></li>
    <li><%= link_to "Log in", '/login' %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="">
    <meta name="author" content="Kirk Jarvis">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar navbar-inverse">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        
          <%= render 'layouts/footer' %>
    
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>